### ISSUE TITLE
Support for "empty labels"

### ISSUE THREAD

**Issue by Zheoni** [01mf02/codesnake#2]
Hello! I found this library after our problem with `ariadne` not being updated. I quite often use the ability to highlight code without any annotation (the first image, in `ariadne`), but with `codesnake` I get an extra line (second image). Is there any possibility to add this feature to `codesnake`?

![image](https://github.com/user-attachments/assets/6a8a4538-0abb-4b21-b659-f52c939ba71a)

![image](https://github.com/user-attachments/assets/47a4b3a1-2a62-44a6-a6cf-272dc9284821)

**Comment by 01mf02** [comment]
By the way, I just checked out cooklang; it is an awesome idea!

**Comment by 01mf02** [comment]
I actually made some tests myself now (b88654cec1ad8706a1609e960ac7b72b2b82aad3); feel free to contribute more.

**Comment by Zheoni** [comment]
Hi, sorry for the late response. Thank you so much! This library was much easier to integrate than ariadne.

> By the way, I just checked out cooklang; it is an awesome idea!

Thanks! It's not my idea though, I did the Rust implementation and the [chef CLI](https://github.com/Zheoni/cooklang-chef).


> I actually made some tests myself now ([b88654c](https://github.com/01mf02/codesnake/commit/b88654cec1ad8706a1609e960ac7b72b2b82aad3)); feel free to contribute more.

I think it should be fine as it is. Also these things are hard to test because if any styling/design changes you have to carefully craft the tests again. If I find any quirk, I will try to fix it and implement a test 😄
